# Generated by Django 6.0.7 on 2026-07-19 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('book_photo', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('author_photo', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('pages', models.IntegerField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rental_price_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rental_period', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('available', 'Available'), ('rented', 'Rented'), ('sold', 'Sold')], max_length=50, null=True)),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lms_app.category')),
            ],
        ),
    ]
