# Generated by Django 6.0.7 on 2026-07-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='pages',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
