# Generated by Django 6.0.7 on 2026-07-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0002_alter_books_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='total_rental',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
